# Generated by Django 5.0.8 on 2026-02-16 10:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_purchaseorder_product_cost_price_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(choices=[('unit', 'Units'), ('kg', 'Kg')], default='unit', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.CharField(choices=[('unit', 'Units'), ('kg', 'Kg')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
