# Generated by Django 6.0.2 on 2026-03-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_make_customer_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='dues_days',
            field=models.IntegerField(default=7, help_text='Default number of days for invoice due date (used when creating invoices)'),
        ),
    ]
