# Generated by Django 4.2.28 on 2026-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_dues_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='auto_print_dialog',
            field=models.BooleanField(default=True, help_text='When enabled, print dialog opens automatically when you click Print (one less step).'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='printer_name',
            field=models.CharField(blank=True, help_text='Exact Windows printer name (e.g. "POS-80 Series Printer"). Leave blank to use default printer.', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='printer_type',
            field=models.CharField(choices=[('thermal_80mm', 'Thermal 80mm (e.g. POS-80)'), ('thermal_58mm', 'Thermal 58mm'), ('a4', 'A4 / Letter (standard)')], default='thermal_80mm', help_text='Invoice layout when printing', max_length=20),
        ),
    ]
