# Generated by Django 4.2.28 on 2026-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_printer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='print_service_url',
            field=models.CharField(blank=True, default='http://localhost:8765', help_text='URL of the local print service (e.g. http://localhost:8765). Only used when Direct Print is enabled.', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='use_direct_print',
            field=models.BooleanField(default=False, help_text='When enabled, bills print silently to configured printer (no dialog). Requires local print service to be running.'),
        ),
    ]
