# Generated by Django 6.0.5 on 2026-08-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_merge_20260314_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='rental_item',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='renteditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnhistory',
            name='rented_item',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='tv_voice_gender',
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
        migrations.DeleteModel(
            name='RentedItem',
        ),
        migrations.DeleteModel(
            name='ReturnHistory',
        ),
    ]
