# Generated by Django 6.0.5 on 2026-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_remove_advancepayment_rental_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='enable_token_system',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='print_token_enabled',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='tv_announce_voice',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='tv_ready_sound',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='tv_ready_sound_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='token_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='token_ready_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='token_status',
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='print_bill_enabled',
            field=models.BooleanField(default=True, help_text='When on, bill/invoice is included when printing.'),
        ),
    ]
