# Generated by Django 6.0.5 on 2026-08-13 13:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_remove_companysettings_enable_token_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Herbs', max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('unit', 'Units/Pieces')], default='kg', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=5, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_id', models.CharField(max_length=50, unique=True)),
                ('production_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('batch_number', models.CharField(max_length=100)),
                ('mfg_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('manufacturing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_items', to='billing.manufacturinglog')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Units of product created per batch', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='billing.product')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.rawmaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_product', 'Finished Product')], max_length=20)),
                ('movement_type', models.CharField(choices=[('opening_stock', 'Opening Stock'), ('purchase', 'Purchase Entry'), ('manufacturing_consumption', 'Manufacturing Consumption'), ('manufacturing_output', 'Manufacturing Output'), ('sale', 'Invoice Sale'), ('sale_cancellation', 'Sale Restored / Cancelled'), ('adjustment', 'Manual Adjustment'), ('return', 'Return')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('previous_balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='billing.product')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='billing.rawmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
