# Generated by Django 5.0.1 on 2025-05-15 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, help_text='Total GST percentage (e.g., 18 for 18%)', max_digits=5)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('invoice_footer_text', models.TextField(blank=True)),
                ('min_rental_days', models.IntegerField(default=1, help_text='Minimum number of days for rental')),
                ('max_rental_days', models.IntegerField(default=30, help_text='Maximum number of days for rental')),
                ('default_rental_days', models.IntegerField(default=7, help_text='Default number of days for rental')),
                ('daily_late_fee', models.DecimalField(decimal_places=2, default=5.0, help_text='Daily late fee percentage', max_digits=5)),
                ('grace_period', models.IntegerField(default=1, help_text='Grace period in days before late fees apply')),
                ('max_late_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum late fee percentage', max_digits=5)),
                ('security_deposit_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Security deposit as percentage of rental value', max_digits=5)),
                ('min_security_deposit', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum security deposit amount', max_digits=10)),
                ('max_security_deposit', models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum security deposit amount', max_digits=10)),
                ('weekly_discount', models.DecimalField(decimal_places=2, default=5.0, help_text='Discount percentage for weekly rentals', max_digits=5)),
                ('monthly_discount', models.DecimalField(decimal_places=2, default=10.0, help_text='Discount percentage for monthly rentals', max_digits=5)),
                ('max_discount', models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum discount percentage', max_digits=5)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'New Rental'), ('return', 'Item Returned'), ('bill', 'Bill Generated'), ('advance', 'Advance Payment'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='daily_rental_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('rent', 'Rental'), ('sale', 'Sale')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='RentedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rent_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('returned_quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_final_bill_generated', models.BooleanField(default=False)),
                ('bill_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='billing.renteditem')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('returned_quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rented_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_history', to='billing.renteditem')),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
    ]
