# Generated by Django 5.2.12 on 2026-03-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_token_alter_invoice_customer_name'),
        ('billing', '0019_tv_voice_gender'),
    ]

    operations = [
    ]
