# Generated by Django 6.0.5 on 2026-08-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_rawmaterial_manufacturinglog_manufacturingitemlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturinglog',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='other_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='raw_material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
