# Generated by Django 6.0.5 on 2026-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_slideshow_options_remove_slideshow_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slideshows/'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slideshows/'),
        ),
    ]
