# Generated by Django 6.0.5 on 2026-08-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_slideshow_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional portrait/mobile image (recommended ~9:16 or 3:4).', null=True, upload_to='slideshows/'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='mobile_video',
            field=models.FileField(blank=True, help_text='Optional portrait/mobile video. Falls back to desktop video if empty.', null=True, upload_to='slideshows/'),
        ),
    ]
