from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProductViewSet,
    StockViewSet,
    InvoiceViewSet,
    dashboard,
    products,
    stock,
    reports,
    reports_export,
    add_product,
    edit_product,
    update_stock,
    delete_product,
    invoices,
    create_invoice,
    api_search_customers,
    edit_invoice,
    delete_invoice,
    view_invoice,
    mark_invoice_paid,
    company_settings,
    generate_invoice_pdf,
    invoice_print,
    api_print_invoice,
    update_threshold,
    invoice_gallery,
    delete_all_invoices,
    backup_restore,
    check_pendrive,
    start_backup,
    start_restore,
    get_backup_history,
    api_get_printers,
    customers,
    payment_received,
    customer_ledger,
    dues_summary,
    purchase_orders,
    create_purchase_order,
    purchase_order_detail,
    purchase_order_print,
    receive_purchase_order,
    balance_sheet,
    add_category,
    delete_category,
)

router = DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'stock', StockViewSet)
router.register(r'invoices', InvoiceViewSet)

app_name = 'billing'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('products/', products, name='products'),
    path('products/add/', add_product, name='add_product'),
    path('categories/add/', add_category, name='add_category'),
    path('categories/<int:pk>/delete/', delete_category, name='delete_category'),
    path('products/<int:pk>/edit/', edit_product, name='edit_product'),
    path('products/<int:pk>/update-stock/', update_stock, name='update_stock'),
    path('products/<int:pk>/delete/', delete_product, name='delete_product'),
    path('stock/', stock, name='stock'),
    path('stock/update/<int:product_id>/', update_stock, name='update_stock'),
    path('stock/threshold/<int:product_id>/', update_threshold, name='update_threshold'),
    path('customers/', customers, name='customers'),
    path('dues/', dues_summary, name='dues_summary'),
    path('payment-received/', payment_received, name='payment_received'),
    path('customer-ledger/<int:customer_id>/', customer_ledger, name='customer_ledger'),
    path('invoices/', invoices, name='invoices'),
    path('invoices/gallery/', invoice_gallery, name='invoice_gallery'),
    path('invoices/create/', create_invoice, name='create_invoice'),
    path('api/invoice-customers/', api_search_customers, name='api_search_customers'),
    path('invoices/<int:pk>/', view_invoice, name='view_invoice'),
    path('invoices/<int:pk>/edit/', edit_invoice, name='edit_invoice'),
    path('invoices/<int:pk>/delete/', delete_invoice, name='delete_invoice'),
    path('invoices/<int:pk>/mark-paid/', mark_invoice_paid, name='mark_invoice_paid'),
    path('invoices/<int:invoice_id>/pdf/', generate_invoice_pdf, name='generate_invoice_pdf'),
    path('invoices/<int:pk>/print/', invoice_print, name='invoice_print'),
    path('api/invoices/<int:pk>/print/', api_print_invoice, name='api_print_invoice'),
    path('reports/', reports, name='reports'),
    path('reports/export/', reports_export, name='reports_export'),
    path('balance-sheet/', balance_sheet, name='balance_sheet'),
    path('settings/', company_settings, name='company_settings'),
    path('invoices/delete-all/', delete_all_invoices, name='delete_all_invoices'),
    path('backup-restore/', backup_restore, name='backup_restore'),
    path('api/check-pendrive/', check_pendrive, name='check_pendrive'),
    path('api/printers/', api_get_printers, name='api_printers'),
    path('api/start-backup/', start_backup, name='start_backup'),
    path('api/start-restore/', start_restore, name='start_restore'),
    path('api/backup-history/', get_backup_history, name='get_backup_history'),
    # Purchase Orders
    path('purchase-orders/', purchase_orders, name='purchase_orders'),
    path('purchase-orders/create/', create_purchase_order, name='create_purchase_order'),
    path('purchase-orders/<int:pk>/', purchase_order_detail, name='purchase_order_detail'),
    path('purchase-orders/<int:pk>/print/', purchase_order_print, name='purchase_order_print'),
    path('purchase-orders/<int:pk>/receive/', receive_purchase_order, name='receive_purchase_order'),
    path('api/', include('billing.api_urls')),
]